USE [master]
GO

/****** Object:  Database [COMS]    Script Date: 04/24/2014 11:21:41 *****/
/* Note: Set the filepath for your SQL Directory*/
CREATE DATABASE [COMS] ON  PRIMARY 
( NAME = N'COMS_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.2\MSSQL\Data\COMS_Data.mdf' , SIZE = 16512KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'COMS_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.2\MSSQL\Data\COMS_Log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
GO

ALTER DATABASE [COMS] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [COMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [COMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [COMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [COMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [COMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [COMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [COMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [COMS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [COMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [COMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [COMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [COMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [COMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [COMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [COMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [COMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [COMS] SET  ENABLE_BROKER 
GO

ALTER DATABASE [COMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [COMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [COMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [COMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [COMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [COMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [COMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [COMS] SET  READ_WRITE 
GO

ALTER DATABASE [COMS] SET RECOVERY FULL 
GO

ALTER DATABASE [COMS] SET  MULTI_USER 
GO

ALTER DATABASE [COMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [COMS] SET DB_CHAINING OFF 
GO


