{"success": true, "total": 215, "records": [
	{ "id" : 1, "value" : "Acute Lymphoblastic Leukemia, Adult"},
	{ "id" : 2, "value" : "Acute Lymphoblastic Leukemia, Childhood"},
	{ "id" : 3, "value" : "Acute Myeloid Leukemia, Adult"},
	{ "id" : 4, "value" : "Acute Myeloid Leukemia, Childhood"},
	{ "id" : 5, "value" : "Adrenocortical Carcinoma"},
	{ "id" : 6, "value" : "Adrenocortical Carcinoma, Childhood"},
	{ "id" : 7, "value" : "AIDS-Related Cancers"},
	{ "id" : 8, "value" : "AIDS-Related Lymphoma"},
	{ "id" : 9, "value" : "Anal Cancer"},
	{ "id" : 10, "value" : "Appendix Cancer"},
	{ "id" : 11, "value" : "Astrocytoma, Childhood Cerebellar"},
	{ "id" : 12, "value" : "Astrocytoma, Childhood Cerebral"},
	{ "id" : 13, "value" : "Basal Cell Carcinoma, see Skin Cancer (Nonmelanoma)"},
	{ "id" : 14, "value" : "Bile Duct Cancer, Extrahepatic"},
	{ "id" : 15, "value" : "Bladder Cancer"},
	{ "id" : 16, "value" : "Bladder Cancer, Childhood"},
	{ "id" : 17, "value" : "Bone Cancer, Osteosarcoma and Malignant Fibrous Histiocytoma"},
	{ "id" : 18, "value" : "Brain Stem Glioma, Childhood"},
	{ "id" : 19, "value" : "Brain Tumor, Adult"},
	{ "id" : 20, "value" : "Brain Tumor, Brain Stem Glioma, Childhood"},
	{ "id" : 21, "value" : "Brain Tumor, Central Nervous System Embryonal Tumors, Childhood"},
	{ "id" : 22, "value" : "Brain Tumor, Cerebellar Astrocytoma, Childhood"},
	{ "id" : 23, "value" : "Brain Tumor, Cerebral Astrocytoma/Malignant Glioma, Childhood"},
	{ "id" : 24, "value" : "Brain Tumor, Ependymoblastoma, Childhood"},
	{ "id" : 25, "value" : "Brain Tumor, Ependymoma, Childhood"},
	{ "id" : 26, "value" : "Brain Tumor, Medulloblastoma, Childhood"},
	{ "id" : 27, "value" : "Brain Tumor, Medulloepithelioma, Childhood"},
	{ "id" : 28, "value" : "Brain Tumor, Pineal Parenchymal Tumors of Intermediate Differentiation, Childhood"},
	{ "id" : 29, "value" : "Brain Tumor, Supratentorial Primitive Neuroectodermal Tumors and Pineoblastoma, Childhood"},
	{ "id" : 30, "value" : "Brain Tumor, Visual Pathway and Hypothalamic Glioma, Childhood"},
	{ "id" : 31, "value" : "Brain and Spinal Cord Tumors, Childhood (Other)"},
	{ "id" : 32, "value" : "Breast Cancer"},
	{ "id" : 33, "value" : "Breast Cancer and Pregnancy"},
	{ "id" : 34, "value" : "Breast Cancer, Childhood"},
	{ "id" : 35, "value" : "Breast Cancer, Male"},
	{ "id" : 36, "value" : "Bronchial Tumors, Childhood"},
	{ "id" : 37, "value" : "Burkitt Lymphoma"},
	{ "id" : 38, "value" : "Carcinoid Tumor, Childhood"},
	{ "id" : 39, "value" : "Carcinoid Tumor,Gastrointestinal"},
	{ "id" : 40, "value" : "Carcinoma of Head and Neck"},
	{ "id" : 41, "value" : "Central Nervous System Embryonal Tumors, Childhood"},
	{ "id" : 42, "value" : "Central Nervous System Lymphoma, Primary"},
	{ "id" : 43, "value" : "Cerebellar Astrocytoma, Childhood"},
	{ "id" : 44, "value" : "Cerebral Astrocytoma/Malignant Glioma, Childhood"},
	{ "id" : 45, "value" : "Cervical Cancer"},
	{ "id" : 46, "value" : "Cervical Cancer, Childhood"},
	{ "id" : 47, "value" : "Childhood Cancers"},
	{ "id" : 48, "value" : "Chordoma, Childhood"},
	{ "id" : 49, "value" : "Chronic Lymphocytic Leukemia"},
	{ "id" : 50, "value" : "Chronic Myelogenous Leukemia"},
	{ "id" : 51, "value" : "Chronic Myeloproliferative Disorders"},
	{ "id" : 52, "value" : "Colorectal Cancer"},
	{ "id" : 53, "value" : "Cutaneous T-Cell Lymphoma, see Mycosis Fungoides and Sézary Syndrome"},
	{ "id" : 54, "value" : "Embryonal Tumors, Central Nervous System, Childhood"},
	{ "id" : 55, "value" : "Endometrial Cancer"},
	{ "id" : 56, "value" : "Ependymoblastoma, Childhood"},
	{ "id" : 57, "value" : "Ependymoma, Childhood"},
	{ "id" : 58, "value" : "Esophageal Cancer"},
	{ "id" : 59, "value" : "Esophageal Cancer, Childhood"},
	{ "id" : 60, "value" : "Ewing Family of Tumors"},
	{ "id" : 61, "value" : "Extracranial Germ Cell Tumor, Childhood"},
	{ "id" : 62, "value" : "Extragonadal Germ Cell Tumor"},
	{ "id" : 63, "value" : "Extrahepatic Bile Duct Cancer"},
	{ "id" : 64, "value" : "Eye Cancer, Intraocular Melanoma"},
	{ "id" : 65, "value" : "Eye Cancer, Retinoblastoma"},
	{ "id" : 66, "value" : "Gallbladder Cancer"},
	{ "id" : 67, "value" : "Gastric (Stomach) Cancer"},
	{ "id" : 68, "value" : "Gastric (Stomach) Cancer, Childhood"},
	{ "id" : 69, "value" : "Gastrointestinal Carcinoid Tumor"},
	{ "id" : 70, "value" : "Gastrointestinal Stromal Tumor (GIST)"},
	{ "id" : 71, "value" : "Gastrointestinal Stromal Cell Tumor, Childhood"},
	{ "id" : 72, "value" : "Germ Cell Tumor, Extracranial, Childhood"},
	{ "id" : 73, "value" : "Germ Cell Tumor, Extragonadal"},
	{ "id" : 74, "value" : "Germ Cell Tumor, Ovarian"},
	{ "id" : 75, "value" : "Gestational Trophoblastic Tumor"},
	{ "id" : 76, "value" : "Glioma, Adult"},
	{ "id" : 77, "value" : "Glioma, Childhood Brain Stem"},
	{ "id" : 78, "value" : "Glioma, Childhood Cerebral Astrocytoma"},
	{ "id" : 79, "value" : "Glioma, Childhood Visual Pathway and Hypothalamic"},
	{ "id" : 80, "value" : "Hairy Cell Leukemia"},
	{ "id" : 81, "value" : "Head and Neck Cancer"},
	{ "id" : 82, "value" : "Hepatocellular (Liver) Cancer, Adult (Primary)"},
	{ "id" : 83, "value" : "Hepatocellular (Liver) Cancer, Childhood (Primary)"},
	{ "id" : 84, "value" : "Hodgkin Lymphoma, Adult"},
	{ "id" : 85, "value" : "Hodgkin Lymphoma, Childhood"},
	{ "id" : 86, "value" : "Hypopharyngeal Cancer"},
	{ "id" : 87, "value" : "Hypothalamic and Visual Pathway Glioma, Childhood"},
	{ "id" : 88, "value" : "Intraocular Melanoma"},
	{ "id" : 89, "value" : "Islet Cell Tumors (Endocrine Pancreas)"},
	{ "id" : 90, "value" : "Kaposi Sarcoma"},
	{ "id" : 91, "value" : "Kidney (Renal Cell) Cancer"},
	{ "id" : 92, "value" : "Kidney Cancer"},
	{ "id" : 93, "value" : "Laryngeal Cancer"},
	{ "id" : 94, "value" : "Laryngeal Cancer, Childhood"},
	{ "id" : 95, "value" : "Leukemia, Acute Lymphoblastic, Adult"},
	{ "id" : 96, "value" : "Leukemia, Acute Lymphoblastic, Childhood"},
	{ "id" : 97, "value" : "Leukemia, Acute Myeloid, Adult"},
	{ "id" : 98, "value" : "Leukemia, Acute Myeloid, Childhood"},
	{ "id" : 99, "value" : "Leukemia, Chronic Lymphocytic"},
	{ "id" : 100, "value" : "Leukemia, Chronic Myelogenous"},
	{ "id" : 101, "value" : "Leukemia, Hairy Cell"},
	{ "id" : 102, "value" : "Lip and Oral Cavity Cancer"},
	{ "id" : 103, "value" : "Liver Cancer, Adult (Primary)"},
	{ "id" : 104, "value" : "Liver Cancer, Childhood (Primary)"},
	{ "id" : 105, "value" : "Lung Cancer, Non-Small Cell"},
	{ "id" : 106, "value" : "Lung Cancer, Small Cell"},
	{ "id" : 107, "value" : "Lymphoma, AIDS-Related"},
	{ "id" : 108, "value" : "Lymphoma, Burkitt"},
	{ "id" : 109, "value" : "Lymphoma, Cutaneous T-Cell, see Mycosis Fungoides and Sézary Syndrome"},
	{ "id" : 110, "value" : "Lymphoma, Hodgkin, Adult"},
	{ "id" : 111, "value" : "Lymphoma, Hodgkin, Childhood"},
	{ "id" : 112, "value" : "Lymphoma, Non-Hodgkin, Adult"},
	{ "id" : 113, "value" : "Lymphoma, Non-Hodgkin, Childhood"},
	{ "id" : 114, "value" : "Lymphoma, Primary Central Nervous System"},
	{ "id" : 115, "value" : "Macroglobulinemia, Waldenstr&ouml;m"},
	{ "id" : 116, "value" : "Malignant Fibrous Histiocytoma of Bone and Osteosarcoma"},
	{ "id" : 117, "value" : "Medulloblastoma, Childhood"},
	{ "id" : 118, "value" : "Medulloepithelioma, Childhood"},
	{ "id" : 119, "value" : "Melanoma"},
	{ "id" : 120, "value" : "Melanoma, Intraocular (Eye)"},
	{ "id" : 121, "value" : "Merkel Cell Carcinoma"},
	{ "id" : 122, "value" : "Mesothelioma, Adult Malignant"},
	{ "id" : 123, "value" : "Mesothelioma, Childhood"},
	{ "id" : 124, "value" : "Metastatic Squamous Neck Cancer with Occult Primary"},
	{ "id" : 125, "value" : "Mouth Cancer"},
	{ "id" : 126, "value" : "Multiple Endocrine Neoplasia Syndrome, Childhood"},
	{ "id" : 127, "value" : "Multiple Myeloma/Plasma Cell Neoplasm"},
	{ "id" : 128, "value" : "Mycosis Fungoides"},
	{ "id" : 129, "value" : "Myelodysplastic Syndromes"},
	{ "id" : 130, "value" : "Myelodysplastic/Myeloproliferative Diseases"},
	{ "id" : 131, "value" : "Myelogenous Leukemia, Chronic"},
	{ "id" : 132, "value" : "Myeloid Leukemia, Adult Acute"},
	{ "id" : 133, "value" : "Myeloid Leukemia, Childhood Acute"},
	{ "id" : 134, "value" : "Myeloma, Multiple"},
	{ "id" : 135, "value" : "Myeloproliferative Disorders, Chronic"},
	{ "id" : 136, "value" : "Nasal Cavity and Paranasal Sinus Cancer"},
	{ "id" : 137, "value" : "Nasopharyngeal Cancer"},
	{ "id" : 138, "value" : "Nasopharyngeal Cancer, Childhood"},
	{ "id" : 139, "value" : "Neuroblastoma"},
	{ "id" : 140, "value" : "Non-Hodgkin Lymphoma, Adult"},
	{ "id" : 141, "value" : "Non-Hodgkin Lymphoma, Childhood"},
	{ "id" : 142, "value" : "Non-Small Cell Lung Cancer"},
	{ "id" : 143, "value" : "Oral Cancer, Childhood"},
	{ "id" : 144, "value" : "Oral Cavity Cancer, Lip and"},
	{ "id" : 145, "value" : "Oropharyngeal Cancer"},
	{ "id" : 146, "value" : "Osteosarcoma and Malignant Fibrous Histiocytoma of Bone"},
	{ "id" : 147, "value" : "Ovarian Cancer, Childhood"},
	{ "id" : 148, "value" : "Ovarian Epithelial Cancer"},
	{ "id" : 149, "value" : "Ovarian Germ Cell Tumor"},
	{ "id" : 150, "value" : "Ovarian Low Malignant Potential Tumor"},
	{ "id" : 151, "value" : "Pancreatic Cancer"},
	{ "id" : 152, "value" : "Pancreatic Cancer, Childhood"},
	{ "id" : 153, "value" : "Pancreatic Cancer, Islet Cell Tumors"},
	{ "id" : 154, "value" : "Papillomatosis, Childhood"},
	{ "id" : 155, "value" : "Paranasal Sinus and Nasal Cavity Cancer"},
	{ "id" : 156, "value" : "Parathyroid Cancer"},
	{ "id" : 157, "value" : "Penile Cancer"},
	{ "id" : 158, "value" : "Pharyngeal Cancer"},
	{ "id" : 159, "value" : "Pheochromocytoma"},
	{ "id" : 160, "value" : "Pineal Parenchymal Tumors of Intermediate Differentiation, Childhood"},
	{ "id" : 161, "value" : "Pineoblastoma and Supratentorial Primitive Neuroectodermal Tumors, Childhood"},
	{ "id" : 162, "value" : "Pituitary Tumor"},
	{ "id" : 163, "value" : "Plasma Cell Neoplasm/Multiple Myeloma"},
	{ "id" : 164, "value" : "Pleuropulmonary Blastoma"},
	{ "id" : 165, "value" : "Pregnancy and Breast Cancer"},
	{ "id" : 166, "value" : "Primary Central Nervous System Lymphoma"},
	{ "id" : 167, "value" : "Prostate Cancer"},
	{ "id" : 168, "value" : "Rectal Cancer"},
	{ "id" : 169, "value" : "Renal Cell (Kidney Cancer)"},
	{ "id" : 170, "value" : "Renal Cell (Kidney) Cancer, Childhood"},
	{ "id" : 171, "value" : "Renal Pelvis and Ureter, Transitional Cell Cancer"},
	{ "id" : 172, "value" : "Respiratory Tract Carcinoma Involving the NUT Gene on Chromosome 15"},
	{ "id" : 173, "value" : "Retinoblastoma"},
	{ "id" : 174, "value" : "Rhabdomyosarcoma, Childhood"},
	{ "id" : 175, "value" : "Salivary Gland Cancer"},
	{ "id" : 176, "value" : "Salivary Gland Cancer, Childhood"},
	{ "id" : 177, "value" : "Sarcoma, Ewing Family of Tumors"},
	{ "id" : 178, "value" : "Sarcoma, Kaposi"},
	{ "id" : 179, "value" : "Sarcoma, Soft Tissue, Adult"},
	{ "id" : 180, "value" : "Sarcoma, Soft Tissue, Childhood"},
	{ "id" : 181, "value" : "Sarcoma, Uterine"},
	{ "id" : 182, "value" : "Sézary Syndrome"},
	{ "id" : 183, "value" : "Skin Cancer (Nonmelanoma)"},
	{ "id" : 184, "value" : "Skin Cancer, Childhood"},
	{ "id" : 185, "value" : "Skin Cancer - Melanoma"},
	{ "id" : 186, "value" : "Skin Carcinoma, Merkel Cell"},
	{ "id" : 187, "value" : "Small Cell Lung Cancer"},
	{ "id" : 188, "value" : "Small Intestine Cancer"},
	{ "id" : 189, "value" : "Soft Tissue Sarcoma, Adult"},
	{ "id" : 190, "value" : "Soft Tissue Sarcoma, Childhood"},
	{ "id" : 191, "value" : "Squamous Cell Carcinoma, see Skin Cancer (Nonmelanoma)"},
	{ "id" : 192, "value" : "Squamous Neck Cancer with Occult Primary, Metastatic"},
	{ "id" : 193, "value" : "Stomach (Gastric) Cancer"},
	{ "id" : 194, "value" : "Stomach (Gastric) Cancer, Childhood"},
	{ "id" : 195, "value" : "Supratentorial Primitive Neuroectodermal Tumors, Childhood"},
	{ "id" : 196, "value" : "T-Cell Lymphoma, Cutaneous, see Mycosis Fungoides and Sézary Syndrome"},
	{ "id" : 197, "value" : "Testicular Cancer"},
	{ "id" : 198, "value" : "Throat Cancer"},
	{ "id" : 199, "value" : "Thymoma and Thymic Carcinoma"},
	{ "id" : 200, "value" : "Thymoma and Thymic Carcinoma, Childhood"},
	{ "id" : 201, "value" : "Thyroid Cancer"},
	{ "id" : 202, "value" : "Thyroid Cancer, Childhood"},
	{ "id" : 203, "value" : "Transitional Cell Cancer of the Renal Pelvis and Ureter"},
	{ "id" : 204, "value" : "Trophoblastic Tumor, Gestational"},
	{ "id" : 205, "value" : "Unknown Primary Site, Cancer of, Childhood"},
	{ "id" : 206, "value" : "Unusual Cancers of Childhood"},
	{ "id" : 207, "value" : "Ureter and Renal Pelvis, Transitional Cell Cancer"},
	{ "id" : 208, "value" : "Urethral Cancer"},
	{ "id" : 209, "value" : "Uterine Cancer, Endometrial"},
	{ "id" : 210, "value" : "Uterine Sarcoma"},
	{ "id" : 211, "value" : "Vaginal Cancer, Childhood"},
	{ "id" : 212, "value" : "Visual Pathway and Hypothalamic Glioma, Childhood"},
	{ "id" : 213, "value" : "Vulvar Cancer"},
	{ "id" : 214, "value" : "Wilms Tumor"},
	{ "id" : 215, "value" : "Women's Cancers"}
]}